kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: httpd-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webservers
    spec:
      containers:
      - name: httpd-container
        image: gcr.io/$PROJECT_ID/test-image:latest
        ports:
        - containerPort: 80